/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Homework3;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void example1(){
        App app = new App();
        String[] black={"","2H","3D","5S","9C","KD"};
        String[] white={"","2C","3H","4S","8C","AH"};
        String exceptedResult = app.whoWins(black,white);
        Assertions.assertEquals( "White wins", exceptedResult);
    }

    @Test void example2(){
        App app = new App();
        String[] black={"","2H","4S","4C","2D","4H"};
        String[] white={"","2S","8S","AS","QS","3S"};
        String exceptedResult = app.whoWins(black,white);
        Assertions.assertEquals( "White wins", exceptedResult);
    }

    @Test void example3(){
        App app = new App();
        String[] black={"","2H","3H","5H","9H","KH"};
        String[] white={"","2C","3H","4S","5C","6H"};
        String exceptedResult = app.whoWins(black,white);
        Assertions.assertEquals( "Black wins", exceptedResult);
    }

    @Test void example4(){
        App app = new App();
        String[] black={"","2H","3D","5S","9C","KD"};
        String[] white={"","2S","3H","5C","9S","KH"};
        String exceptedResult = app.whoWins(black,white);
        Assertions.assertEquals( "Tie", exceptedResult);
    }
}
